/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package midtermklaklouk;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SpringLayout;
import javax.swing.Timer;

/**
 *
 * @author SnaMiracle
 */
public class KlaKlouk extends javax.swing.JFrame {

    int w = 100, h = 100;
    double AMOUNT_PER_BET = 500; //CORRECT ?
    double balance = 20000.0;
    double[] playerBet = new double[6];
    int[] result = new int[3];

    /**
     * Creates new form KlaKlouk
     */
    public KlaKlouk() {
        initComponents();
        lblDepo.setText("ទឹកប្រាក់: ៛" + balance);
        txtKla.setFocusable(false);
        txtKlok.setFocusable(false);
        txtHen.setFocusable(false);
        txtLobster.setFocusable(false);
        txtCrab.setFocusable(false);
        txtFish.setFocusable(false);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    public String[] images = {
        "Resources/Untitled-1.jpg",
        "Resources/Untitled-2.jpg",
        "Resources/Untitled-3.jpg",
        "Resources/Untitled-4.jpg",
        "Resources/Untitled-5.jpg",
        "Resources/Untitled-6.jpg"
    };

    Random random = new Random();

    Timer timer = new Timer(100, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            result[0] = random.nextInt(6);
            result[1] = random.nextInt(6);
            result[2] = random.nextInt(6);

            Image im = new ImageIcon(this.getClass().getResource(images[result[0]])).getImage().getScaledInstance(w, h, Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(im);
            lblRandom1.setIcon(icon);

            Image im2 = new ImageIcon(this.getClass().getResource(images[result[1]])).getImage().getScaledInstance(w, h, Image.SCALE_SMOOTH);
            ImageIcon icon2 = new ImageIcon(im2);
            lblRandom2.setIcon(icon2);

            Image im3 = new ImageIcon(this.getClass().getResource(images[result[2]])).getImage().getScaledInstance(w, h, Image.SCALE_SMOOTH);
            ImageIcon icon3 = new ImageIcon(im3);
            lblRandom3.setIcon(icon3);

        }
    });

    private void betFunction(double amount, int betOnIndex, javax.swing.JTextField textLabel) {
        try {
            // Add 500 to the current value
            double res = Math.max(balance, 0); // Avoid negative result
            if (res == 0) {
                playerBet[betOnIndex] += 0.0;
            } else {
                playerBet[betOnIndex] += amount;
            }
            //calculateBetMoney(playerBet[betOnIndex]);
            calculateBetMoney(amount);
            textLabel.setText(String.valueOf(playerBet[betOnIndex]));
            textLabel.setHorizontalAlignment(JTextField.CENTER);
        } catch (NumberFormatException ex) {
            // Handle the case where the current text is not a valid double
            ex.printStackTrace();
        }
    }

    private void clearBetFunction(int betOnIndex, javax.swing.JTextField textLabel) {
        try {
            double amount = Double.parseDouble(textLabel.getText());
            double res = Math.max(amount, 0); // Avoid negative result

            if (res == 0) {
                playerBet[betOnIndex] = 0.0;
            } else {
                playerBet[betOnIndex] -= amount;
            }

            balance += amount;
            lblDepo.setText("ទឹកប្រាក់: ៛" + balance);
            
            textLabel.setText(String.valueOf(playerBet[betOnIndex]));
            textLabel.setHorizontalAlignment(JTextField.CENTER);
        } catch (NumberFormatException ex) {
            // Handle the case where the current text is not a valid double
            ex.printStackTrace();
        }
    }

    private double calculateBetMoney(double betAmt) {
        double tempBalance = balance;
        balance -= betAmt;
        double res = Math.max(balance, 0); // Avoid negative result
        if (res == 0) {
            //res = balance;
            balance = tempBalance;
            JOptionPane.showMessageDialog(null, "លុយអត់គ្រប់ផងចង់លេង!!!");
        }
        lblDepo.setText("ទឹកប្រាក់: ៛" + res);
        return res;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblKlouk = new javax.swing.JLabel();
        lblKla = new javax.swing.JLabel();
        lblHen = new javax.swing.JLabel();
        lblLobster = new javax.swing.JLabel();
        lblCrab = new javax.swing.JLabel();
        lblFish = new javax.swing.JLabel();
        txtKla = new javax.swing.JTextField();
        txtKlok = new javax.swing.JTextField();
        txtHen = new javax.swing.JTextField();
        txtLobster = new javax.swing.JTextField();
        txtCrab = new javax.swing.JTextField();
        txtFish = new javax.swing.JTextField();
        lblDepo = new javax.swing.JLabel();
        lblRandom1 = new javax.swing.JLabel();
        lblRandom2 = new javax.swing.JLabel();
        lblRandom3 = new javax.swing.JLabel();
        btnAboutUs = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        btnKlasMinus = new javax.swing.JButton();
        btnKlockMinus = new javax.swing.JButton();
        btnHenMinus = new javax.swing.JButton();
        btnLobsterMinus = new javax.swing.JButton();
        btnCrabMinus = new javax.swing.JButton();
        btnFishMinus = new javax.swing.JButton();
        testLabel = new javax.swing.JLabel();
        logOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("KlaKloukGaming");
        setBackground(javax.swing.UIManager.getDefaults().getColor("Button.default.focusedBackground"));

        jLabel1.setFont(new java.awt.Font("AvertaStd-Regular", 0, 36)); // NOI18N
        jLabel1.setText("KlaKlouk Gaming");

        lblKlouk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/midtermklaklouk/Resources/Klock.png"))); // NOI18N
        lblKlouk.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 3, true));
        lblKlouk.setPreferredSize(new java.awt.Dimension(150, 150));
        lblKlouk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKloukMouseClicked(evt);
            }
        });

        lblKla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/midtermklaklouk/Resources/Tiger.png"))); // NOI18N
        lblKla.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 3, true));
        lblKla.setPreferredSize(new java.awt.Dimension(150, 150));
        lblKla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKlaMouseClicked(evt);
            }
        });

        lblHen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/midtermklaklouk/Resources/hen.png"))); // NOI18N
        lblHen.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 3, true));
        lblHen.setPreferredSize(new java.awt.Dimension(150, 150));
        lblHen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHenMouseClicked(evt);
            }
        });

        lblLobster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/midtermklaklouk/Resources/Lobster.jpg.png"))); // NOI18N
        lblLobster.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 3, true));
        lblLobster.setPreferredSize(new java.awt.Dimension(150, 150));
        lblLobster.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLobsterMouseClicked(evt);
            }
        });

        lblCrab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/midtermklaklouk/Resources/Kdam.jpg.png"))); // NOI18N
        lblCrab.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 3, true));
        lblCrab.setPreferredSize(new java.awt.Dimension(150, 150));
        lblCrab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCrabMouseClicked(evt);
            }
        });

        lblFish.setIcon(new javax.swing.ImageIcon(getClass().getResource("/midtermklaklouk/Resources/Fish.jpg.png"))); // NOI18N
        lblFish.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 3, true));
        lblFish.setPreferredSize(new java.awt.Dimension(150, 150));
        lblFish.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFishMouseClicked(evt);
            }
        });

        txtKla.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtKla.setCaretColor(new java.awt.Color(255, 255, 255));
        txtKla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKlaActionPerformed(evt);
            }
        });

        txtKlok.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtHen.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtLobster.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtCrab.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtFish.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblDepo.setFont(new java.awt.Font("Khmer OS Siemreap", 1, 18)); // NOI18N
        lblDepo.setText("ទឹកប្រាក់:");

        lblRandom1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 3, true));
        lblRandom1.setPreferredSize(new java.awt.Dimension(150, 150));

        lblRandom2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 3, true));
        lblRandom2.setPreferredSize(new java.awt.Dimension(150, 150));

        lblRandom3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 3, true));
        lblRandom3.setPreferredSize(new java.awt.Dimension(150, 150));

        btnAboutUs.setFont(new java.awt.Font("Khmer OS Siemreap", 1, 14)); // NOI18N
        btnAboutUs.setText("About Us");
        btnAboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutUsActionPerformed(evt);
            }
        });

        btnStart.setFont(new java.awt.Font("Khmer OS Siemreap", 1, 18)); // NOI18N
        btnStart.setText("ក្រឡុក");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnStop.setFont(new java.awt.Font("Khmer OS Siemreap", 1, 18)); // NOI18N
        btnStop.setText("ឈប់");
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        btnKlasMinus.setBackground(new java.awt.Color(255, 0, 0));
        btnKlasMinus.setText("-");
        btnKlasMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKlasMinusActionPerformed(evt);
            }
        });

        btnKlockMinus.setBackground(new java.awt.Color(255, 0, 0));
        btnKlockMinus.setText("-");
        btnKlockMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKlockMinusActionPerformed(evt);
            }
        });

        btnHenMinus.setBackground(new java.awt.Color(255, 0, 0));
        btnHenMinus.setText("-");
        btnHenMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHenMinusActionPerformed(evt);
            }
        });

        btnLobsterMinus.setBackground(new java.awt.Color(255, 0, 0));
        btnLobsterMinus.setText("-");
        btnLobsterMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLobsterMinusActionPerformed(evt);
            }
        });

        btnCrabMinus.setBackground(new java.awt.Color(255, 0, 0));
        btnCrabMinus.setText("-");
        btnCrabMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrabMinusActionPerformed(evt);
            }
        });

        btnFishMinus.setBackground(new java.awt.Color(255, 0, 0));
        btnFishMinus.setText("-");
        btnFishMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFishMinusActionPerformed(evt);
            }
        });

        logOut.setText("Logout");
        logOut.setToolTipText("");
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblKla, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtKla, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnKlasMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(txtLobster, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnLobsterMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblLobster, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblKlouk, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtKlok, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnKlockMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCrab, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCrabMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblCrab, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblHen, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtHen, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnHenMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFish, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnFishMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblFish, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAboutUs, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(133, 133, 133))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(61, 61, 61)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblRandom2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblRandom3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(59, 59, 59)
                                                .addComponent(lblRandom1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addContainerGap(37, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDepo, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(testLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(logOut)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(logOut, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblKlouk, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblKla, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHen, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtKla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnKlasMinus))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtKlok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnKlockMinus))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtHen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnHenMinus)))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLobster, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCrab, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFish, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLobster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCrab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLobsterMinus)
                            .addComponent(btnCrabMinus)
                            .addComponent(btnFishMinus)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRandom1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblRandom2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRandom3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAboutUs, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDepo)
                    .addComponent(testLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutUsActionPerformed
        // TODO add your handling code here:
        about_us aboutUs = new about_us();
        aboutUs.show();
    }//GEN-LAST:event_btnAboutUsActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        // TODO add your handling code here:
        if (txtKla.getText().isEmpty()
                && txtKlok.getText().isEmpty()
                && txtHen.getText().isEmpty()
                && txtLobster.getText().isEmpty()
                && txtCrab.getText().isEmpty()
                && txtFish.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "អត់ចាក់ផងចង់ឈ្នះ!!!");
        } else {
            timer.start();
        }
    }//GEN-LAST:event_btnStartActionPerformed

    private void resultCheck() {
        double winAmount = 0.0;
        double totalBet = 0.0;
        String resultindex = "";
        
        for (int i = 0; i < 3; i++) {
            winAmount += playerBet[result[i]];
            resultindex += String.valueOf(result[i]) + " , ";
        }
        
        for (double bet : playerBet) {
            totalBet += bet;
        }
        
        testLabel.setText(resultindex);
        
        if(winAmount > 0) {
            balance += winAmount;
            JOptionPane.showMessageDialog(null, "You win : " + winAmount);
        }else {
            balance -= totalBet;
            JOptionPane.showMessageDialog(null, "You Lost! " + totalBet);
        }
        
        playerBet = new double[6];
        result = new int[3];
        lblDepo.setText("ទឹកប្រាក់: ៛" + balance);
    }
    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        // TODO add your handling code here:
        timer.stop();

        resultCheck();
        txtKla.setText("");
        txtKlok.setText("");
        txtHen.setText("");
        txtLobster.setText("");
        txtCrab.setText("");
        txtFish.setText("");
    }//GEN-LAST:event_btnStopActionPerformed

    private void txtKlaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKlaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKlaActionPerformed

    private void lblKlaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKlaMouseClicked
        // TODO add your handling code here:
        betFunction(AMOUNT_PER_BET, 0, txtKla);
    }

    /*
private void btnKlasMinusActionPerformed(java.awt.event.ActionEvent evt) {
  
    }//GEN-LAST:event_lblKlaMouseClicked
*/
    private void btnKlasMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKlasMinusActionPerformed
        // TODO add your handling code here: 
        clearBetFunction(0, txtKla);
        txtKla.setText("");
    }//GEN-LAST:event_btnKlasMinusActionPerformed

    private void lblKloukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKloukMouseClicked
        // TODO add your handling code here:
        betFunction(AMOUNT_PER_BET, 1, txtKlok);
    }//GEN-LAST:event_lblKloukMouseClicked

    private void btnKlockMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKlockMinusActionPerformed
        // TODO add your handling code here:
            clearBetFunction(1, txtKlok);
            txtKlok.setText("");
    }//GEN-LAST:event_btnKlockMinusActionPerformed

    private void lblHenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHenMouseClicked
        // TODO add your handling code here:
        betFunction(AMOUNT_PER_BET, 2, txtHen);
    }//GEN-LAST:event_lblHenMouseClicked

    private void lblLobsterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLobsterMouseClicked
        // TODO add your handling code here:
        betFunction(AMOUNT_PER_BET, 3, txtLobster);
    }//GEN-LAST:event_lblLobsterMouseClicked

    private void lblCrabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCrabMouseClicked
        // TODO add your handling code here:
        betFunction(AMOUNT_PER_BET, 4, txtCrab);
    }//GEN-LAST:event_lblCrabMouseClicked

    private void lblFishMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFishMouseClicked
        // TODO add your handling code here:
        betFunction(AMOUNT_PER_BET, 5, txtFish);
    }//GEN-LAST:event_lblFishMouseClicked

    private void btnHenMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHenMinusActionPerformed
        // TODO add your handling code here:
            clearBetFunction(2, txtHen);
            txtHen.setText("");
    }//GEN-LAST:event_btnHenMinusActionPerformed

    private void btnLobsterMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLobsterMinusActionPerformed
        // TODO add your handling code here:
            clearBetFunction(3, txtLobster);
            txtLobster.setText("");
    }//GEN-LAST:event_btnLobsterMinusActionPerformed

    private void btnCrabMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrabMinusActionPerformed
        // TODO add your handling code here:
            clearBetFunction(4, txtCrab);
            txtCrab.setText("");
    }//GEN-LAST:event_btnCrabMinusActionPerformed

    private void btnFishMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFishMinusActionPerformed
        // TODO add your handling code here:
            clearBetFunction(5, txtFish);
            txtFish.setText("");
    }//GEN-LAST:event_btnFishMinusActionPerformed

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        // TODO add your handling code here:
        loginformKK loginkk = new loginformKK();
        loginkk.show();
        this.dispose();
    }//GEN-LAST:event_logOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KlaKlouk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KlaKlouk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KlaKlouk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KlaKlouk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KlaKlouk().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAboutUs;
    private javax.swing.JButton btnCrabMinus;
    private javax.swing.JButton btnFishMinus;
    private javax.swing.JButton btnHenMinus;
    private javax.swing.JButton btnKlasMinus;
    private javax.swing.JButton btnKlockMinus;
    private javax.swing.JButton btnLobsterMinus;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCrab;
    private javax.swing.JLabel lblDepo;
    private javax.swing.JLabel lblFish;
    private javax.swing.JLabel lblHen;
    private javax.swing.JLabel lblKla;
    private javax.swing.JLabel lblKlouk;
    private javax.swing.JLabel lblLobster;
    private javax.swing.JLabel lblRandom1;
    private javax.swing.JLabel lblRandom2;
    private javax.swing.JLabel lblRandom3;
    private javax.swing.JButton logOut;
    private javax.swing.JLabel testLabel;
    private javax.swing.JTextField txtCrab;
    private javax.swing.JTextField txtFish;
    private javax.swing.JTextField txtHen;
    private javax.swing.JTextField txtKla;
    private javax.swing.JTextField txtKlok;
    private javax.swing.JTextField txtLobster;
    // End of variables declaration//GEN-END:variables

    private int getImageIndex(String[] images) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
